# Generated by Django 5.0.4 on 2024-06-28 13:20

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('hostname', models.CharField(blank=True, max_length=30, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=30, null=True)),
                ('uptime', models.CharField(blank=True, max_length=200, null=True)),
                ('last_changes_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSensor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('hostname', models.CharField(blank=True, max_length=30, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=30, null=True)),
                ('uptime', models.CharField(blank=True, max_length=200, null=True)),
                ('last_changes_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sensor',
                'verbose_name_plural': 'historical sensors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
