# Generated by Django 5.0.4 on 2024-04-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('sensor_id', models.IntegerField()),
                ('protocol', models.CharField(choices=[('SNMPv2', 'snmp2'), ('TCP', 'tcp')], default='SNMPv2', max_length=20)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SNMPSettings',
            fields=[
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sensors.sensor')),
                ('temp_oid', models.CharField(max_length=200)),
                ('community', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TCPSettings',
            fields=[
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sensors.sensor')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
