# Generated by Django 5.0.4 on 2024-04-27 19:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_oid', models.CharField(max_length=40)),
                ('community', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TCPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSensor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('probe_sens_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('protocol', models.CharField(choices=[('SNMPv2', 'SNMPv2'), ('TCP', 'TCP')], default='TCP', max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=30, null=True)),
                ('last_changes_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hostname', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sensors.host')),
            ],
            options={
                'verbose_name': 'historical sensor',
                'verbose_name_plural': 'historical sensors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_sens_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('protocol', models.CharField(choices=[('SNMPv2', 'SNMPv2'), ('TCP', 'TCP')], default='TCP', max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=30, null=True)),
                ('last_changes_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.host')),
            ],
        ),
    ]
