# Generated by Django 5.0.4 on 2024-04-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='uptime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='uptime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('hostname', 'ip')},
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['hostname', 'ip'], name='sensors_hostnam_4d3908_idx'),
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensors',
        ),
    ]
