# Generated by Django 5.0.4 on 2024-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_historicalsensor_heat_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
