# Generated by Django 5.0.4 on 2024-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_historicalsensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
