# Generated by Django 5.0.4 on 2024-04-28 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_options_historicalsensor_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
