# Generated by Django 5.0.4 on 2024-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_historicalsensor_temperature_sensor_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsensor',
            name='port',
        ),
        migrations.RemoveField(
            model_name='historicalsensor',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='port',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='tcpsettings',
            name='ip',
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='probe_sens_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='probe_sens_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snmpsettings',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
