# Generated by Django 5.0.4 on 2024-04-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_historicalsensor_last_update_sensor_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpsettings',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
        migrations.AlterField(
            model_name='historicalsensor',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
