# Generated by Django 5.0.4 on 2024-04-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_snmpsettings_sensor_alter_historicalsensor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpsettings',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
    ]
