# Generated by Django 5.0.4 on 2024-06-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensordata_remove_historicalsensor_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='uptime',
            field=models.DateTimeField(),
        ),
    ]
