# Generated by Django 5.0.4 on 2024-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_snmpsettings_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpsettings',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
