# Generated by Django 5.0.4 on 2024-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_sensordata_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='uptime',
            field=models.CharField(max_length=50),
        ),
    ]
