# Generated by Django 5.0.4 on 2024-04-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_remove_snmpsettings_sensor_remove_tcpsettings_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='error',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='error',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
