# Generated by Django 5.0.4 on 2024-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_sensordata_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='heat_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
