# Generated by Django 5.0.4 on 2024-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_remove_historicalsensor_protocol_choose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcpsettings',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
