# Generated by Django 5.0.4 on 2024-07-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_alter_sensordata_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
